trigger:
- main

pool:
  name: Default

stages:
  - stage: Copy
    jobs:
      - job: CopyFiles
        steps:
          - task: CopyFiles@2
            displayName: 'Copy Files to Artifacts'
            inputs:
              SourceFolder: 'LogicApp-Temp'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)'

  - stage: Zip
    jobs:
      - job: ZipFiles
        steps:
        - task: ArchiveFiles@2
          displayName: 'Archive LogicApp-Temp'
          inputs:
            rootFolderOrFile: 'LogicApp-Temp'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true

  - stage: Publish
    jobs:
      - job: PublishFiles
        steps:
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          

