resources:
 repositories:
   - repository: ARM-Templates
     type: github
     ref: LogicApp-Temp
     name: paweadi/ARM-Templates
     endpoint: paweadi
parameters:
  - name: Build
    displayName: Choose value
    type: string
    values:
      - adf
      - logicapp
      - eventhub
      - ARM-Templates
      
pool:
  name: Default

  - stage: Copy
    jobs:
    - job: Copyfiles
      steps:
      - task: CopyFiles@1
        displayName: 'Copy files to AZ Artifacts'
        inputs:
          SourceFolder: 'LogicApp-Temp'
          TargetFolder: '$(build.artifactstagingdirectory)'

  - stage: Zip
    jobs:
    - job: ArchiveFiles
      steps:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'LogicApp-Temp'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

  - stage: publish
    jobs:
    - job: PublishArtifacts
      steps: 
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'