pool:
  name: Default

stages:
  - stage: Copy
    jobs:
      - job: CopyFiles
        steps:
        - task: CopyFiles@2
          displayName: 'Copy Files to Azure Artifacts'
          inputs:
            SourceFolder: 'LogicApp-Temp'
            TargetFolder: '$(build.artifactstagingdirectory)'

  - stage: Archive
    jobs: 
      - job: Archivefiles
        steps:
        - task: ArchiveFiles@2
          displayName: 'Archive LogicApp-Temp'
          inputs:
            rootFolderOrFile: 'LogicApp-Temp'

  - stage: Publish
    jobs:
      - job: Publishfiles
        steps: 
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: LogicApp'
          inputs:
            ArtifactName: LogicApp
