pool:
  name: Default

stages:
- stage: Copy
  jobs:
  - job: Copyfiles
    steps:
    - task: CopyFiles@1
      displayName: 'Copy files to AZ Artifacts'
      inputs:
        SourceFolder: 'LogicApp-Temp'
        TargetFolder: '$(build.artifactstagingdirectory)'

- stage: Archieve
  jobs:
  - job: ArchieveFiles
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive LogicApp-Temp'
      inputs:
        rootFolderOrFile: 'LogicApp-Temp'

- stage: Publish
  jobs:
  - job: PublishArtifacts
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
         ArtifactName: LogicApp