trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'https://raw.githubusercontent.com/paweadi/ARM-Templates/main/LogicApp-Temp/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactSatagingDirectory)'
