trigger:
- main

pool:
  name: Default

stages:
  - stage: Copy
    jobs:
      - job: CopyFiles
        steps:
          - task: CopyFiles@2
            displayName: 'Copy Files to Artifacts'
            inputs:
              SourceFolder: 'LogicApp-Temp'
              TargetFolder: '$(build.artifactstagingdirectory)'

  - stage: Zip file
    jobs:
      - job: ZipFiles
        steps:
        - task: ArchiveFiles@2
          displayName: 'Archive LogicApp-Temp'
          inputs:
           rootFolderOrFile: 'LogicApp-Temp'

  - stage: Publish
    jobs:
      - job: PublishFiles
        steps:
        - task: PublishBuildArtifacts@1
          inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: 'Container'

