pool:
  name: Default
parameters:
  - name: repo
    type: string
    displayName: 'select repo name'
    values:
      - LogicApp

resources:
 repositories:
   - repository: repo_logicApp
     type: git
     name: paweadi/repo_logicApp
stages:
- stage: Checkout
  jobs:
  - job: Copyfiles
    steps:
    - checkout: none
    - task: CopyFiles@1
      displayName: 'Copy files to AZ Artifacts'
      inputs:
        SourceFolder: 'repo_logicApp'
        TargetFolder: '$(build.artifactstagingdirectory)'

- stage: Zip
  jobs:
  - job: ArchiveFiles
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'repo_logicApp'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

- stage: publish
  jobs:
  - job: PublishArtifacts
    steps: 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'