trigger:
- main

pool:
  name: Default
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to Artifacts'
  inputs:
    SourceFolder: 'LogicApp-Temp'
    TargetFolder: '$(build.artifactstagingdirectory)/LogicApp'

- task: ArchiveFiles@2
  displayName: 'Archive LogicApp-Temp'
  inputs:
    rootFolderOrFile: 'LogicApp-Temp'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'


