pool:
  name: Default

stages:
- stage: Copy
  jobs:
  - job: Copyfiles
    steps:
    - task: CopyFiles@1
      displayName: 'Copy files to AZ Artifacts'
      inputs:
        SourceFolder: 'LogicApp-Temp'
        TargetFolder: '$(build.artifactstagingdirectory)'

- stage: Zip
  jobs:
  - job: ArchiveFiles
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'LogicApp-Temp'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

- stage: Publish
  jobs:
  - job: PublishArtifacts
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
         ArtifactName: LogicApp