pool:
  name: Default

stages:
  - stage: Copy
    jobs:
      - job: CopyFiles
        steps:
        - task: CopyFiles@2
          displayName: 'Copy Files to Azure Artifacts'
          inputs:
            SourceFolder: 'LogicApp-Temp'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)'

  - stage: Archive
    jobs: 
      - job: Archivefiles
        steps:
        - task: ArchiveFiles@2
          displayName: 'Archive LogicApp-Temp'
          inputs:
            rootFolderOrFile: 'LogicApp-Temp'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true

  - stage: Publish
    jobs:
      - job: Publishfiles
        steps: 
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)'
            ArtifactName: 'ARMDrop'
            publishLocation: 'Container'
